<?php

namespace Core\HeurekaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryCategoryRepository extends EntityRepository
{
    public function setHint(\Doctrine\ORM\Query $query)
    {
        return $query->setHint(\Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');
    }

    public function getCategoryCategoryQueryBuilder()
    {
        $queryBuilder = $this->getEntityManager()->createQueryBuilder()
                ->select("hcc, c")
                ->from("CoreHeurekaBundle:CategoryCategory", "hcc")
                ->leftJoin("hcc.category", "c")
                ->addOrderBy("c.lft");

        return $queryBuilder;
    }
    
    public function getCategoryCategoryQuery()
    {
        return $this->setHint($this->getCategoryCategoryQueryBuilder()->getQuery());
    }
}
